apiVersion: entity.humanitec.io/v1b1
kind: Account
metadata:
  id: quickstart-azure
entity:
  name: Quickstart Azure
  type: azure-identity
  credentials:
    azure_identity_tenant_id: f8d886ff-2097-4c25-96a8-6dc1a287954d
    azure_identity_client_id: ecc3f12e-0802-44e0-806f-d25a17c1ef30
